# 베이스 이미지 설정
FROM python:3.9

# 작업 디렉토리 설정
WORKDIR /app

# 필수 라이브러리 설치
RUN apt update && apt install -y wget unzip curl \
    libnss3 libgconf-2-4 libxi6 libx11-xcb1 libxcomposite1 \
    libxcursor1 libxdamage1 libxrandr2 libgbm1 libasound2 \
    libglib2.0-0 fonts-liberation libappindicator3-1 xdg-utils

# Chrome 및 ChromeDriver 설치
RUN apt-get update && apt-get install -y \
    wget \
    gnupg2 \
    apt-transport-https \
    ca-certificates

# Chrome 133 버전 다운로드 및 설치
RUN wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_133.0.6943.98-1_amd64.deb -O chrome.deb \
    && dpkg -i chrome.deb || apt-get install -f -y \
    && rm chrome.deb \
    && google-chrome --version || echo "Chrome installation failed"

# ChromeDriver 다운로드 및 설치 (Chrome 133 버전에 맞는 ChromeDriver 설치)
RUN wget -O /tmp/chromedriver.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/133.0.6943.98/chromedriver-linux64.zip && \
    unzip /tmp/chromedriver.zip -d /tmp/ && \
    mv /tmp/chromedriver-linux64/chromedriver /usr/local/bin/ && \
    chmod +x /usr/local/bin/chromedriver && \
    rm -rf /tmp/chromedriver-linux64 /tmp/chromedriver.zip && \
    chromedriver --version

# 필요한 패키지 설치
COPY requirements.txt .
RUN pip install -r requirements.txt

# 애플리케이션 코드 복사
COPY . .

# Railway에서 PORT 환경 변수를 사용할 수 있도록 설정
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]