# 베이스 이미지 설정
FROM python:3.9

# 작업 디렉토리 설정
WORKDIR /app

# 필수 라이브러리 설치
RUN apt update && apt install -y wget unzip curl \
    libnss3 libgconf-2-4 libxi6 libx11-xcb1 libxcomposite1 \
    libxcursor1 libxdamage1 libxrandr2 libgbm1 libasound2 \
    libglib2.0-0 fonts-liberation libappindicator3-1 xdg-utils

# Chrome 설치
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
    apt update && apt install -y google-chrome-stable

# ChromeDriver 버전 확인 후 다운로드 및 설치
RUN CHROME_DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE) && \
    echo "Installing ChromeDriver version: $CHROME_DRIVER_VERSION" && \
    wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip && \
    unzip /tmp/chromedriver.zip -d /usr/local/bin/ && \
    chmod +x /usr/local/bin/chromedriver && \
    ls -lah /usr/local/bin/chromedriver && \
    /usr/local/bin/chromedriver --version

# 필요한 패키지 설치
COPY requirements.txt .
RUN pip install -r requirements.txt

# 애플리케이션 코드 복사
COPY . .

# Railway에서 PORT 환경 변수를 사용할 수 있도록 설정
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]